artist_data = 

//copy output from http://www.csvjson.com/csv2json below
[
  {
    "ID": 0,
    "artist_name": "Pablo Picasso",
    "date_of_birth": "1881/10/25",
    "date_of_death": "1973/04/08",
  },
  {
    "ID": 1,
    "artist_name": "Vincent van Gogh",
    "date_of_birth": "1853/03/30",
    "date_of_death": "1890/07/29",
  },
  {
    "ID": 2,
    "artist_name": "Salvador Dali",
    "date_of_birth": "1904/05/11",
    "date_of_death": "1989/01/23",
  },
  {
    "ID": 3,
    "artist_name": "Andy Warhol",
    "date_of_birth": "1928/08/06",
    "date_of_death": "1987/02/22",
  },
  {
    "ID": 4,
    "artist_name": "Leonardo da Vinci",
    "date_of_birth": "1452/04/15",
    "date_of_death": "1519/05/02",
  },
  {
    "ID": 5,
    "artist_name": "Claude Monet",
    "date_of_birth": "1840/11/14",
    "date_of_death": "1926/12/05",
  },
  {
    "ID": 6,
    "artist_name": "Henri Matisse",
    "date_of_birth": "1869/12/31",
    "date_of_death": "1954/11/03",
  },
  {
    "ID": 7,
    "artist_name": "Piet Mondrian",
    "date_of_birth": "1874/03/07",
    "date_of_death": "1944/02/01",
  },
  {
    "ID": 8,
    "artist_name": "Georgia O'Keeffe",
    "date_of_birth": "1887/11/15",
    "date_of_death": "1986/03/06",
  },
  {
    "ID": 9,
    "artist_name": "Edgar Degas",
    "date_of_birth": "1834/07/19",
    "date_of_death": "1917/09/27",
  },
  {
    "ID": 10,
    "artist_name": "Marcel Duchamp",
    "date_of_birth": "1887/07/28",
    "date_of_death": "1968/10/02",
  },
  {
    "ID": 11,
    "artist_name": "Jackson Pollock",
    "date_of_birth": "1912/01/28",
    "date_of_death": "1956/08/11",
  },
  {
    "ID": 12,
    "artist_name": "Gustav Klimt",
    "date_of_birth": "1862/07/14",
    "date_of_death": "1918/02/06",
  },
  {
    "ID": 13,
    "artist_name": "Paul Cezanne",
    "date_of_birth": "1839/01/19",
    "date_of_death": "1906/10/22",
  },
  {
    "ID": 14,
    "artist_name": "Rembrandt",
    "date_of_birth": "1606/07/15",
    "date_of_death": "1669/10/04",
  },
  {
    "ID": 15,
    "artist_name": "Paul Klee",
    "date_of_birth": "1879/12/18",
    "date_of_death": "1940/06/29",
  },
  {
    "ID": 16,
    "artist_name": "Frida Kahlo",
    "date_of_birth": "1907/07/06",
    "date_of_death": "1954/07/13",
  },
  {
    "ID": 17,
    "artist_name": "Joan Miro",
    "date_of_birth": 0,
    "date_of_death": "1983/12/25",
  },
  {
    "ID": 18,
    "artist_name": "Paul Gauguin",
    "date_of_birth": "1848/06/07",
    "date_of_death": "1903/05/08",
  },
  {
    "ID": 19,
    "artist_name": "Edvard Munch",
    "date_of_birth": "1863/12/12",
    "date_of_death": "1944/01/23",
  },
  {
    "ID": 20,
    "artist_name": "Pierre-Auguste Renoir",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 21,
    "artist_name": "Roy Lichtenstein",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 22,
    "artist_name": "Raphael",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 23,
    "artist_name": "Marc Chagall",
    "date_of_birth": "1887/07/07",
    "date_of_death": "1985/03/28",
  },
  {
    "ID": 24,
    "artist_name": "Rene Magritte",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 25,
    "artist_name": "Johannes Vermeer",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 26,
    "artist_name": "Georges Seurat",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 27,
    "artist_name": "Mark Rothko",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 28,
    "artist_name": "Edward Hopper",
    "date_of_birth": "1882/07/22",
    "date_of_death": "1967/05/15",
  },
  {
    "ID": 29,
    "artist_name": "Keith Haring",
    "date_of_birth": "1958/05/04",
    "date_of_death": "1990/02/16",
  },
  {
    "ID": 30,
    "artist_name": "Jasper Johns",
    "date_of_birth": "1930/05/15",
    "date_of_death": "1930/05/15",
  },
  {
    "ID": 31,
    "artist_name": "Edouard Manet",
    "date_of_birth": "1832/01/23",
    "date_of_death": "1883/04/30",
  },
  {
    "ID": 32,
    "artist_name": "Caravaggio",
    "date_of_birth": "1571/09/29",
    "date_of_death": "1610/07/18",
  },
  {
    "ID": 33,
    "artist_name": "Grant Wood",
    "date_of_birth": "1891/02/13",
    "date_of_death": "1942/02/12",
  },
  {
    "ID": 34,
    "artist_name": "Francisco Goya",
    "date_of_birth": "1746/03/30",
    "date_of_death": "1828/04/16",
  },
  {
    "ID": 35,
    "artist_name": "Titian",
    "date_of_birth": 0,
    "date_of_death": "1576/08/27",
  },
  {
    "ID": 36,
    "artist_name": "Norman Rockwell",
    "date_of_birth": "1894/02/03",
    "date_of_death": "1978/11/08",
  },
  {
    "ID": 37,
    "artist_name": "Peter Paul Rubens",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 38,
    "artist_name": "Willem de Kooning",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 39,
    "artist_name": "Sandro Botticelli",
    "date_of_birth": "1445/03/01",
    "date_of_death": "1510/05/17",
  },
  {
    "ID": 40,
    "artist_name": "Diego Rivera",
    "date_of_birth": "1886/12/08",
    "date_of_death": "1957/11/24",
  },
  {
    "ID": 41,
    "artist_name": "El Greco",
    "date_of_birth": "1541/??/??",
    "date_of_death": "1614/04/07",
  },
  {
    "ID": 42,
    "artist_name": "Mary Cassatt",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 43,
    "artist_name": "Albrecht Durer",
    "date_of_birth": "1471/05/21",
    "date_of_death": "1528/04/06",
  },
  {
    "ID": 44,
    "artist_name": "Jean-Michel Basquiat",
    "date_of_birth": "1960/12/22",
    "date_of_death": "1988/08/12",
  },
  {
    "ID": 45,
    "artist_name": "Camille Pissarro",
    "date_of_birth": "1830/07/10",
    "date_of_death": "1903/11/13",
  },
  {
    "ID": 46,
    "artist_name": "Pieter Bruegel the Elder",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 47,
    "artist_name": "Georges Braque",
    "date_of_birth": "1882/05/13",
    "date_of_death": "1963/08/31",
  },
  {
    "ID": 48,
    "artist_name": "Damien Hirst",
    "date_of_birth": "1965/06/07",
    "date_of_death": "1965/06/07",
  },
  {
    "ID": 49,
    "artist_name": "Gerhard Richter",
    "date_of_birth": "1932/09/02",
    "date_of_death": 0,
  },
  {
    "ID": 50,
    "artist_name": "Mike Kelley",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 51,
    "artist_name": "John Baldessari",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 52,
    "artist_name": "Matthew Barney",
    "date_of_birth": "1967/03/25",
    "date_of_death": "1967/03/25",
  },
  {
    "ID": 53,
    "artist_name": "Albert Oehlen",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 54,
    "artist_name": "Richard Prince",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 55,
    "artist_name": "Vito Acconci",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 56,
    "artist_name": "Anish Kapoor",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 57,
    "artist_name": "Louise Bourgeois",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 58,
    "artist_name": "Jose Bemal",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 59,
    "artist_name": "Takashi Murakami",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 60,
    "artist_name": "Sol LeWitt",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 61,
    "artist_name": "Rita Ackermann",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 62,
    "artist_name": "Lucian Freud",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 63,
    "artist_name": "Chuck Close",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 64,
    "artist_name": "Olafur Eliasson",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 65,
    "artist_name": "Ida Applebroog",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 66,
    "artist_name": "Eija-Liisa Ahtila",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 67,
    "artist_name": "Jo Baer",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 68,
    "artist_name": "Maurice Benayoun",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 69,
    "artist_name": "Ashley Bickeron",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 70,
    "artist_name": "Vanessa Beecroft",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 71,
    "artist_name": "Artur Barrio",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 72,
    "artist_name": "Chantal Akerman",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 73,
    "artist_name": "Peggy Ahwesh",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 74,
    "artist_name": "Marina Abramovic",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 75,
    "artist_name": "Cai Guo-Qiang",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 76,
    "artist_name": "Tom Friedman",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 77,
    "artist_name": "Marlene Dumas",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 78,
    "artist_name": "Donald Judd",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 79,
    "artist_name": "Ana Mendieta",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 80,
    "artist_name": "Frank Stella",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 81,
    "artist_name": "Zhang Huan",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 82,
    "artist_name": "Yayoi Kusama",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 83,
    "artist_name": "Bruce Nauman",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 84,
    "artist_name": "Edward Ruscha",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 85,
    "artist_name": "Anselm Kiefer",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 86,
    "artist_name": "Jenny Holzer",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 87,
    "artist_name": "Jeff Wall",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 88,
    "artist_name": "Antony Gormley",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 89,
    "artist_name": "Egon Schiele",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 90,
    "artist_name": "Cy Twombly",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 91,
    "artist_name": "Max Emst",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 92,
    "artist_name": "Franz Kline",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 93,
    "artist_name": "Hans Hofmann",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 94,
    "artist_name": "Helen Frankenthaler",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 95,
    "artist_name": "Robert Delaunay",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 96,
    "artist_name": "Barnett Newman",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 97,
    "artist_name": "Antoni Tapies",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 98,
    "artist_name": "Fernand Leger",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 99,
    "artist_name": "Kurt Scwitters",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 100,
    "artist_name": "Brice Marden",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 101,
    "artist_name": "Amedeo Modigliani",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 102,
    "artist_name": "Alberto Giacometti",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 103,
    "artist_name": "Arshile Gorky",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 104,
    "artist_name": "Jasper Johns",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 105,
    "artist_name": "Toba Khedoori",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 106,
    "artist_name": "Roberto Matta",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 107,
    "artist_name": "Arman",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 108,
    "artist_name": "Robert Indiana",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 109,
    "artist_name": "Robert Rauschenberg",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 110,
    "artist_name": "Balthus",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 111,
    "artist_name": "Thomas Hart Benton",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 112,
    "artist_name": "Umberto Boccioni",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 113,
    "artist_name": "Kenneth Noland",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 114,
    "artist_name": "Jean Dubuffet",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 115,
    "artist_name": "Andre Derain",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 116,
    "artist_name": "JMW Turner",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 117,
    "artist_name": "James McNeill Whistler",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 118,
    "artist_name": "Paul Serusier",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 119,
    "artist_name": "Wassily Kandinsky",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 120,
    "artist_name": "Georges Vantongerloo",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 121,
    "artist_name": "Lyonel Feininger",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 122,
    "artist_name": "Frank Kupka",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 123,
    "artist_name": "Giacomo Balla",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 124,
    "artist_name": "Bart Van Der Leck",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 125,
    "artist_name": "Marsden Hartley",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 126,
    "artist_name": "Kasimir Malevich",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 127,
    "artist_name": "Louis Marcoussis",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 128,
    "artist_name": "Shepard Fairey",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 129,
    "artist_name": "Chantal Joffe",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 130,
    "artist_name": "Njideka Akuny Crosby",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 131,
    "artist_name": "Varda Caivano",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 132,
    "artist_name": "Peter Doig",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 133,
    "artist_name": "Stan Douglas",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 134,
    "artist_name": "Inka Essenhigh",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 135,
    "artist_name": "Idris Khan",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 136,
    "artist_name": "John Korner",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 137,
    "artist_name": "Wangechi Mutu",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 138,
    "artist_name": "Alice Neel",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 139,
    "artist_name": "Chris Ofili",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 140,
    "artist_name": "Suling Wang",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 141,
    "artist_name": "Francesca Woodman",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 142,
    "artist_name": "Gina Beavers",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 143,
    "artist_name": "Dorothy Iannone",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 144,
    "artist_name": "Henning Bohl",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 145,
    "artist_name": "Julia Fish",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 146,
    "artist_name": "Andrew Brischler",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 147,
    "artist_name": "Joseph Pollack",
    "date_of_birth": "1983/06/23",
    "date_of_death": "1983/06/23",
  },
  {
    "ID": 148,
    "artist_name": "Lucy Dodd",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 149,
    "artist_name": "Nicolas Lamas",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 150,
    "artist_name": "Jose Maria Sicilia",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 151,
    "artist_name": "Keith Mayerson",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 152,
    "artist_name": "Jesse Willenbring",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 153,
    "artist_name": "Elizabeth Huey",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 154,
    "artist_name": "Victor Vasarely",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 155,
    "artist_name": "Ellen Carey",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 156,
    "artist_name": "Christo & Jeanne-Claude",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 157,
    "artist_name": "Marilyn Dintenfass",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 158,
    "artist_name": "Eric Fischl",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 159,
    "artist_name": "Kate Shepherd",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 160,
    "artist_name": "Cecily Brown",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 161,
    "artist_name": "Landon Wilson",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 162,
    "artist_name": "Isaac Brest",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 163,
    "artist_name": "Robert Swain",
    "date_of_birth": 0,
    "date_of_death": "1940????",
  },
  {
    "ID": 164,
    "artist_name": "Kate Steciw",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 165,
    "artist_name": "Kika Karadi",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 166,
    "artist_name": "Mark Flood",
    "date_of_birth": 0,
    "date_of_death": "1957????",
  },
  {
    "ID": 167,
    "artist_name": "Kasper Sonne",
    "date_of_birth": 0,
    "date_of_death": "1975????",
  },
  {
    "ID": 168,
    "artist_name": "Joshua Abelow",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 169,
    "artist_name": "Alexander Kroll",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 170,
    "artist_name": "Petra Cortright",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 171,
    "artist_name": "Liang Wei",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 172,
    "artist_name": "Ange Leccia",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 173,
    "artist_name": "Josh Reames",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 174,
    "artist_name": "Michael Craig-Martin",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 175,
    "artist_name": "Julian Opie",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 176,
    "artist_name": "Yue Minjun",
    "date_of_birth": 0,
    "date_of_death": "1962????",
  },
  {
    "ID": 177,
    "artist_name": "Zhang Xiaogang",
    "date_of_birth": 0,
    "date_of_death": "1958????",
  },
  {
    "ID": 178,
    "artist_name": "Matthew Ritchie",
    "date_of_birth": 0,
    "date_of_death": "1964????",
  },
  {
    "ID": 179,
    "artist_name": "Robert Longo",
    "date_of_birth": 0,
    "date_of_death": "1953????",
  },
  {
    "ID": 180,
    "artist_name": "David Salle",
    "date_of_birth": 0,
    "date_of_death": "1952????",
  },
  {
    "ID": 181,
    "artist_name": "Lucy Winton",
    "date_of_birth": 0,
    "date_of_death": 0,
  },
  {
    "ID": 182,
    "artist_name": "Martin Creed",
    "date_of_birth": 0,
    "date_of_death": "1968????",
  }
]