"use client";

import { FormEvent, useState } from "react";

import type { GameplaySettings } from "@/server/game-settings";

export default function GameplaySettingsForm({
  initialSettings,
}: {
  initialSettings: GameplaySettings;
}) {
  const [settings, setSettings] = useState(initialSettings);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);

  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setBusy(true);
    setMessage("");
    setError("");

    try {
      const response = await fetch("/api/admin/gameplay-settings", {
        method: "PATCH",
        headers: { "content-type": "application/json" },
        body: JSON.stringify(settings),
      });
      const body = (await response.json()) as {
        error?: string;
        settings?: GameplaySettings;
      };
      if (!response.ok || !body.settings) {
        throw new Error(body.error ?? "Gameplay settings could not be saved.");
      }
      setSettings(body.settings);
      setMessage("Gameplay settings saved.");
    } catch (saveError) {
      setError(
        saveError instanceof Error
          ? saveError.message
          : "Gameplay settings could not be saved.",
      );
    } finally {
      setBusy(false);
    }
  }

  return (
    <form className="admin-settings-form" onSubmit={submit}>
      <SettingField
        description="Minutes between uses of the daily drop button."
        label="Daily drop cooldown"
        max={10080}
        onChange={(value) =>
          setSettings((current) => ({
            ...current,
            dailyDropCooldownMinutes: value,
          }))
        }
        suffix="minutes"
        value={settings.dailyDropCooldownMinutes}
      />
      <SettingField
        description="Number of unclaimed items generated by each daily drop."
        label="Daily drop item count"
        max={100}
        onChange={(value) =>
          setSettings((current) => ({ ...current, dailyDropCount: value }))
        }
        suffix="items"
        value={settings.dailyDropCount}
      />
      <SettingField
        description="How often displayed artwork settles prorated money and XP."
        label="Gallery money/XP payout interval"
        max={1440}
        onChange={(value) =>
          setSettings((current) => ({
            ...current,
            galleryPayoutIntervalMinutes: value,
          }))
        }
        suffix="minutes"
        value={settings.galleryPayoutIntervalMinutes}
      />

      <button disabled={busy} type="submit">
        {busy ? "saving..." : "save gameplay settings"}
      </button>
      {message ? <p className="admin-success">{message}</p> : null}
      {error ? <p className="admin-error">{error}</p> : null}
    </form>
  );
}

function SettingField({
  label,
  description,
  value,
  max,
  suffix,
  onChange,
}: {
  label: string;
  description: string;
  value: number;
  max: number;
  suffix: string;
  onChange: (value: number) => void;
}) {
  return (
    <label className="admin-setting">
      <span>
        <strong>{label}</strong>
        <small>{description}</small>
      </span>
      <span className="admin-setting-input">
        <input
          max={max}
          min={1}
          onChange={(event) => onChange(Number(event.target.value))}
          required
          type="number"
          value={value}
        />
        {suffix}
      </span>
    </label>
  );
}
